services:
  bot:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env.development
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: go.mod
          target: /usr/src/mimo/go.mod
        - action: sync+restart
          path: ./
          target: /usr/src/mimo