services:
  bot:
    container_name: bot
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    image: furina-bot
    restart: unless-stopped
    env_file: .env.development
    depends_on:
      - database
    volumes:
      - .:/workspaces/furina:cached

  database:
    container_name: database
    image: postgres:15.8
    restart: unless-stopped
    env_file: .env.development
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: