services:
  bot:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env.development
    develop:
      watch:
        - action: rebuild
          path: go.mod
          target: /usr/src/mimo/go.mod
        - action: sync+restart
          path: ./
          target: /usr/src/mimo