services:
  dev-container:
    image: mcr.microsoft.com/devcontainers/go:1-1.23-bookworm
    command: sleep infinity
    volumes:
      - .:/workspaces/mimo:cached

  bot:
    container_name: bot
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env.development
    depends_on:
      - database
    develop:
      watch:
        - action: rebuild
          path: go.mod
          target: /usr/src/mimo/go.mod
        - action: sync+restart
          path: ./
          target: /usr/src/mimo

  database:
    container_name: database
    image: postgres:15.8
    restart: unless-stopped
    env_file: .env.development
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: