--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.12 (Debian 15.12-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: discord_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.discord_users (
    id bigint NOT NULL,
    guild_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.discord_users OWNER TO postgres;

--
-- Name: TABLE discord_users; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.discord_users IS 'Discord users';


--
-- Name: game_regions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.game_regions (
    id bigint NOT NULL,
    name text NOT NULL,
    reset_time timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.game_regions OWNER TO postgres;

--
-- Name: TABLE game_regions; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.game_regions IS 'Game server regions';


--
-- Name: game_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.game_users (
    id bigint NOT NULL,
    discord_id bigint NOT NULL,
    game_id bigint NOT NULL,
    region_id bigint NOT NULL,
    modified_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.game_users OWNER TO postgres;

--
-- Name: TABLE game_users; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.game_users IS 'HoYoverse game users';


--
-- Name: games; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.games (
    id bigint NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.games OWNER TO postgres;

--
-- Name: TABLE games; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.games IS 'HoYoverse games';


--
-- Name: games_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hoyolab_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hoyolab_users (
    id bigint NOT NULL,
    discord_id bigint NOT NULL,
    ltoken_v2 text NOT NULL,
    ltmid_v2 text NOT NULL,
    modified_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.hoyolab_users OWNER TO postgres;

--
-- Name: TABLE hoyolab_users; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.hoyolab_users IS 'HoYoLAB tokens';


--
-- Name: regions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.game_regions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.regions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: game_regions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.game_regions (id, name, reset_time, created_at) VALUES (1, 'Asia', '2020-09-19 20:00:00+00', '2025-04-13 17:30:47.573831+00');
INSERT INTO public.game_regions (id, name, reset_time, created_at) VALUES (2, 'America', '2020-09-20 09:00:00+00', '2025-04-13 17:30:47.573831+00');
INSERT INTO public.game_regions (id, name, reset_time, created_at) VALUES (3, 'Europe', '2020-09-19 03:00:00+00', '2025-04-13 17:30:47.573831+00');


--
-- Data for Name: games; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.games (id, name, created_at) VALUES (1, 'Genshin Impact', '2025-04-11 10:50:44.253485+00');
INSERT INTO public.games (id, name, created_at) VALUES (2, 'Honkai: Star Rail', '2025-04-11 10:50:44.253485+00');
INSERT INTO public.games (id, name, created_at) VALUES (3, 'Zenless Zone Zero', '2025-04-11 10:50:44.253485+00');


--
-- Name: games_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.games_id_seq', 3, true);


--
-- Name: regions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.regions_id_seq', 3, true);


--
-- Name: discord_users discord_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.discord_users
    ADD CONSTRAINT discord_users_pkey PRIMARY KEY (id);


--
-- Name: game_users game_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_users
    ADD CONSTRAINT game_users_pkey PRIMARY KEY (id);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);


--
-- Name: hoyolab_users hoyolab_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hoyolab_users
    ADD CONSTRAINT hoyolab_users_pkey PRIMARY KEY (id);


--
-- Name: game_regions regions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_regions
    ADD CONSTRAINT regions_pkey PRIMARY KEY (id);


--
-- Name: game_users game_users_discord_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_users
    ADD CONSTRAINT game_users_discord_id_fkey FOREIGN KEY (discord_id) REFERENCES public.discord_users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: game_users game_users_game_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_users
    ADD CONSTRAINT game_users_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: game_users game_users_region_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_users
    ADD CONSTRAINT game_users_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.game_regions(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: hoyolab_users hoyolab_users_discord_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hoyolab_users
    ADD CONSTRAINT hoyolab_users_discord_id_fkey FOREIGN KEY (discord_id) REFERENCES public.discord_users(id);
