name: build_and_deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCW_SECRET_KEY }}
        registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
    - name: Build Docker Image
      run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/${{ secrets.IMAGE_NAME }}
    - name: Push Docker Image
      run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/${{ secrets.IMAGE_NAME }}
    - name: Deploy Container
      run: >
        curl -X POST \
          -H "X-Auth-Token: ${{ secrets.SCW_SECRET_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}' \
          "https://api.scaleway.com/containers/v1beta1/regions/fr-par/containers/${{ secrets.CONTAINER_ID }}/deploy"
