name: build_and_deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_API_KEY }}
        registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
    - name: Build Docker Image
      run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/mimo
    - name: Push Docker Image
      run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/mimo
